# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :mrkt do
    fmid "MyString"
    marketname "MyString"
    website "MyString"
    street "MyString"
    city "MyString"
    county "MyString"
    state "MyString"
    zip "MyString"
    season1date "MyString"
    season1time "MyString"
    season2date "MyString"
    season2time "MyString"
    season3date "MyString"
    season3time "MyString"
    season4date "MyString"
    season4time "MyString"
    x "MyString"
    y "MyString"
    location "MyString"
    credit "MyString"
    wic "MyString"
    wiccash "MyString"
    sfmnp "MyString"
    snap "MyString"
    bakedgoods "MyString"
    cheese "MyString"
    crafts "MyString"
    flowers "MyString"
    eggs "MyString"
    seafood "MyString"
    herbs "MyString"
    vegetables "MyString"
    honey "MyString"
    jams "MyString"
    maple "MyString"
    meat "MyString"
    nursery "MyString"
    nuts "MyString"
    plants "MyString"
    poultry "MyString"
    prepared "MyString"
    soap "MyString"
    trees "MyString"
    wine "MyString"
    updatetime "MyString"
  end
end
